# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QWidget)
import main_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1230, 665)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.inputVideo = QLabel(self.centralwidget)
        self.inputVideo.setObjectName(u"inputVideo")
        self.inputVideo.setGeometry(QRect(20, 130, 389, 289))
        self.inputVideo.setLayoutDirection(Qt.LeftToRight)
        self.inputVideo.setFrameShape(QFrame.Box)
        self.inputVideo.setFrameShadow(QFrame.Plain)
        self.inputVideo.setAlignment(Qt.AlignCenter)
        self.inputVideo.setWordWrap(False)
        self.inputVideo.setMargin(0)
        self.inputVideo.setOpenExternalLinks(False)
        self.segVideo = QLabel(self.centralwidget)
        self.segVideo.setObjectName(u"segVideo")
        self.segVideo.setGeometry(QRect(420, 130, 389, 289))
        self.segVideo.setLayoutDirection(Qt.LeftToRight)
        self.segVideo.setFrameShape(QFrame.Box)
        self.segVideo.setFrameShadow(QFrame.Plain)
        self.segVideo.setAlignment(Qt.AlignCenter)
        self.segVideo.setWordWrap(False)
        self.segVideo.setMargin(0)
        self.segVideo.setOpenExternalLinks(False)
        self.detVideo = QLabel(self.centralwidget)
        self.detVideo.setObjectName(u"detVideo")
        self.detVideo.setGeometry(QRect(820, 130, 389, 289))
        self.detVideo.setLayoutDirection(Qt.LeftToRight)
        self.detVideo.setFrameShape(QFrame.Box)
        self.detVideo.setFrameShadow(QFrame.Plain)
        self.detVideo.setAlignment(Qt.AlignCenter)
        self.detVideo.setWordWrap(False)
        self.detVideo.setMargin(0)
        self.detVideo.setOpenExternalLinks(False)
        self.beginButton = QPushButton(self.centralwidget)
        self.beginButton.setObjectName(u"beginButton")
        self.beginButton.setGeometry(QRect(1100, 510, 101, 111))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(160, 100, 91, 21))
        font = QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(550, 100, 121, 21))
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(950, 100, 121, 21))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.filePathEdit = QLineEdit(self.centralwidget)
        self.filePathEdit.setObjectName(u"filePathEdit")
        self.filePathEdit.setGeometry(QRect(830, 510, 261, 31))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(950, 470, 121, 21))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 480, 111, 91))
        self.label_5.setPixmap(QPixmap(u":/icon/images/tree.png"))
        self.label_5.setScaledContents(True)
        self.frame = QLineEdit(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(860, 590, 61, 31))
        self.frame.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(830, 595, 31, 21))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(940, 590, 161, 31))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(830, 620, 311, 31))
        self.label_8.setTextFormat(Qt.AutoText)
        self.label_8.setWordWrap(False)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(830, 550, 161, 31))
        self.deviceBox = QComboBox(self.centralwidget)
        self.deviceBox.addItem("")
        self.deviceBox.addItem("")
        self.deviceBox.setObjectName(u"deviceBox")
        self.deviceBox.setGeometry(QRect(920, 550, 171, 31))
        self.deviceBox.setEditable(False)
        self.deviceBox.setCurrentText(u"GPU")
        self.deviceBox.setMaxCount(3)
        self.deviceBox.setSizeAdjustPolicy(QComboBox.AdjustToContentsOnFirstShow)
        self.deviceBox.setMinimumContentsLength(0)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(140, 580, 91, 21))
        self.label_10.setFont(font)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.greenrate = QLabel(self.centralwidget)
        self.greenrate.setObjectName(u"greenrate")
        self.greenrate.setGeometry(QRect(140, 610, 91, 21))
        self.greenrate.setFont(font)
        self.greenrate.setStyleSheet(u"color: rgb(0, 170, 0)")
        self.greenrate.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(270, 580, 91, 21))
        self.label_11.setFont(font)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.buildingrate = QLabel(self.centralwidget)
        self.buildingrate.setObjectName(u"buildingrate")
        self.buildingrate.setGeometry(QRect(270, 610, 91, 21))
        self.buildingrate.setFont(font)
        self.buildingrate.setStyleSheet(u"color: rgb(119, 119, 127)")
        self.buildingrate.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(410, 580, 91, 21))
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(540, 580, 91, 21))
        self.label_13.setFont(font)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.carCount = QLabel(self.centralwidget)
        self.carCount.setObjectName(u"carCount")
        self.carCount.setGeometry(QRect(410, 610, 91, 21))
        self.carCount.setFont(font)
        self.carCount.setAlignment(Qt.AlignCenter)
        self.humanCount = QLabel(self.centralwidget)
        self.humanCount.setObjectName(u"humanCount")
        self.humanCount.setGeometry(QRect(540, 610, 91, 21))
        self.humanCount.setFont(font)
        self.humanCount.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(260, 480, 111, 91))
        self.label_14.setPixmap(QPixmap(u":/icon/images/\u5efa\u7b51.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(400, 500, 111, 91))
        self.label_15.setPixmap(QPixmap(u":/icon/images/\u5c0f\u8f66-\u79c1\u5bb6\u8f66.png"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(550, 500, 81, 61))
        self.label_16.setPixmap(QPixmap(u":/icon/images/\u884c\u4eba.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(1010, 30, 101, 31))
        self.label_17.setPixmap(QPixmap(u":/logo/images/logo.png"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(1130, 30, 81, 31))
        self.label_18.setPixmap(QPixmap(u":/logo/images/intel.png"))
        self.label_18.setScaledContents(True)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(440, 0, 371, 81))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        self.label_19.setFont(font1)
        self.label_19.setStyleSheet(u"color: rgb(0, 0, 255)")
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(1080, 60, 101, 31))
        self.label_20.setTextFormat(Qt.AutoText)
        self.label_20.setWordWrap(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.deviceBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u57fa\u4e8ePaddlePaddle\u7684\u4f4e\u7a7a\u65e0\u4eba\u673a\u667a\u80fd\u5de1\u68c0\u7cfb\u7edf", None))
        self.inputVideo.setText(QCoreApplication.translate("MainWindow", u"\u7b49\u5f85\u89c6\u9891\u4fe1\u53f7\u8f93\u5165\u2026\u2026", None))
        self.segVideo.setText(QCoreApplication.translate("MainWindow", u"\u7b49\u5f85\u89c6\u9891\u4fe1\u53f7\u8f93\u5165\u2026\u2026", None))
        self.detVideo.setText(QCoreApplication.translate("MainWindow", u"\u7b49\u5f85\u89c6\u9891\u4fe1\u53f7\u8f93\u5165\u2026\u2026", None))
        self.beginButton.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u68c0\u6d4b", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u56fe\u50cf", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5730\u7269\u8981\u7d20\u5206\u5272", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u5730\u7269\u76ee\u6807\u68c0\u6d4b", None))
        self.filePathEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u672c\u5730\u822a\u62cd\u89c6\u9891\u6216\u65e0\u4eba\u673artmp\u6e90\u5730\u5740", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c\u533a", None))
        self.label_5.setText("")
        self.frame.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u6bcf", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5e27\u6267\u884c\u4e00\u6b21\u8bed\u4e49\u5206\u5272\u548c\u68c0\u6d4b*", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"* \u5e27\u7387\u8bf7\u6839\u636e\u81ea\u5df1\u7684\u8bbe\u5907\u914d\u7f6e\u8bbe\u7f6e\uff0c\u4e0d\u5efa\u8bae\u8fc7\u5927", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u63a8\u7406\u786c\u4ef6\u9009\u62e9\uff1a", None))
        self.deviceBox.setItemText(0, QCoreApplication.translate("MainWindow", u"GPU", None))
        self.deviceBox.setItemText(1, QCoreApplication.translate("MainWindow", u"CPU", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u7eff\u5730\u7387", None))
        self.greenrate.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u5efa\u7b51\u7387", None))
        self.buildingrate.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u8f66\u8f86\u6570\u91cf", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u884c\u4eba\u6570\u91cf", None))
        self.carCount.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.humanCount.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u4f4e\u7a7a\u65e0\u4eba\u673a\u667a\u80fd\u5de1\u68c0\u7cfb\u7edf", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u4f9b\u8f6f\u786c\u4ef6\u652f\u6301", None))
    # retranslateUi

